GeneralSettings:
  # Url del tracker donde se descargarán los torrents
  ApiUrl: "https://tracker.com"
  # Tu user api key (https://tracker.com/users/YOUR_USERNAME/apikeys)
  ApiKey: "Tu-Api-Key-Aqui"
  # Los Tags que definas en el filtro serán ignorados en la búsqueda
  FilterTags: ["SUBS"]

FolderSettings:
  # Directorio donde se descargarán las películas
  Movies: "/downloads/movies"
  # Directorio donde se descargarán las series
  TV: "/downloads/series"
  # Las series se descargarán en subdirectorios por cada serie y/o temporada, ejemplo:
  # series/Breaking Bad (2008)/Season 01/ -> Se descargará en una carpeta Season solamente si es un single episode
  # series/Breaking Bad (2008)/ -> Se descargará directamente en la carpeta de la serie si es un season pack

TmdbSettings:
  # Url de la api de tmdb (no modificar)
  ApiUrl: "https://api.themoviedb.org/3"
  # Tu api key de tmdb (https://www.themoviedb.org/settings/api)
  ApiKey: "Tu-Api-Key-Aqui"

# Emby es usado para saber si una serie o película ya está descargada en tu librería
EmbySettings:
  # Activa o desactiva el uso de Emby
  Enabled: false
  # Url donde se encuentra tu servidor Emby
  ApiUrl: "http://emby.server.local"
  # Tu api key de Emby (http://emby.local/web/index.html#!/apikeys)
  ApiKey: "fbfb7fd68e744dd3b1300f27f3879cf4"
  # Un usuario de Emby con acceso a todas las bibliotecas
  Username: "jhoan.me"

TorrentClients:
  # Configuración de cada cliente de torrent
  - Url: "http://192.168.1.20:8080"
    DisplayName: "Home"
    Username: "admin"
    Password: "Contraseña1234"
